apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
  namespace: default
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=sqlserver-service,1433;Database=FCG_Users;User Id=SA;Password=FCG_Dev@2024;TrustServerCertificate=True;"
  Jwt__Secret: "FCG_SUPER_SECRET_KEY_CHANGE_IN_PRODUCTION_32CHARS!"
  RabbitMQ__Password: "guest"
